server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.29.4.146:5432/l23o6
    username: postgres
    password: 123456

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
