server:
  port: 8081
spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/sports
      username: postgres
      password: 123456
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/test

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0